# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 7.0
  - 7.1

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

# Dependencies
before_install:
  - composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source $PREFER_LOWEST
